export const MEMORIES_ACTIONS = {
    GET_MEMORIES: "GET_MEMORIES",
    GET_MEMORIES_BY_SEARCH: "GET_MEMORIES_BY_SEARCH",
    GET_MEMORIES_SUCCESS: "GET_MEMORIES_SUCCESS",
    GET_MEMORIES_ERROR: "GET_MEMORIES_ERROR",
    UPDATE_MEMORIES_VIEW: "UPDATE_MEMORIES_VIEW",
    UPDATE_MEMORIES: "UPDATE_MEMORIES",
    CREATE_MEMORIES_SUCCESS: "CREATE_MEMORIES_SUCCESS",
    CREATE_MEMORIES: "CREATE_MEMORIES",
    LIKE_MEMORIES: "LIKE_MEMORIES",
    DELETE_MEMORIES: "DELETE_MEMORIES",
    DELETE_MEMORIES_SUCCESS: "DELETE_MEMORIES_SUCCESS",
    COMMENT_MEMORIES: "COMMENT_MEMORIES",
};
